# Generated by Django 4.0.4 on 2022-05-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='John', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Doe', max_length=50),
        ),
    ]
