# Generated by Django 4.0.4 on 2022-05-04 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applify', '0004_user_is_active_user_staff'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='education',
            table='User',
        ),
    ]
